#!/usr/bin/env python3
"""Validate pinned contract fixtures; --backend checks drift; --update refreshes explicitly."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'contracts/core-1'
GENERATED = ROOT / 'composeApp/src/commonTest/kotlin/com/srisu/srisu/core/CoreContractFixtures.kt'


def generated(fixtures):
    entries = '\n'.join('    const val ' + name + ' = ' + json.dumps(json.dumps(value, separators=(',', ':')), ensure_ascii=True).replace('$', '\\$') for name, value in fixtures.items())
    return '// Generated by tools/core_contracts.py --update. Backend owns these fixtures.\npackage com.srisu.srisu.core\n\nobject CoreContractFixtures {\n' + entries + '\n}\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--backend', type=Path)
    parser.add_argument('--update', action='store_true')
    args = parser.parse_args()
    if args.update and args.backend is None:
        parser.error('--update requires an explicit backend checkout')
    names = ('schema.json', 'fixtures.json', 'manifest.json')
    if args.backend:
        source = args.backend.resolve() / 'contracts/core-1'
        for name in names:
            if args.update:
                TARGET.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source / name, TARGET / name)
            elif (source / name).read_bytes() != (TARGET / name).read_bytes():
                raise SystemExit(f'Contract drift: {name}. Review the backend change before --update.')
    fixtures = json.loads((TARGET / 'fixtures.json').read_text())
    expected = generated(fixtures)
    if args.update: GENERATED.write_text(expected)
    if GENERATED.read_text() != expected: raise SystemExit('Generated KMP fixtures are stale.')
    digest = hashlib.sha256(b''.join((TARGET / name).read_bytes() for name in names)).hexdigest()
    print('core-1 contract snapshot and generated KMP fixtures consistent: ' + digest)


if __name__ == '__main__': main()
